-- ============================================
-- FULL US STATES DATA SEED
-- ============================================

-- 1. Create table (if not exists)
CREATE TABLE IF NOT EXISTS states (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  abbreviation TEXT NOT NULL,
  capital TEXT NOT NULL,
  statehood_date TEXT NOT NULL,
  statehood_order INTEGER NOT NULL,
  area_sq_miles INTEGER NOT NULL,
  population INTEGER NOT NULL,
  population_year INTEGER DEFAULT 2024,
  motto TEXT,
  nickname TEXT,
  flag_description TEXT,
  flower TEXT,
  bird TEXT,
  famous_for TEXT,
  major_employer TEXT,
  political_orientation TEXT,
  senators JSONB DEFAULT '[]',
  representatives_count INTEGER DEFAULT 1,
  state_tax_rate DECIMAL(5,2) DEFAULT 0,
  state_tax_info TEXT,
  flag_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Clear existing entries (optional, if you want a clean start)
-- DELETE FROM states;

-- 3. Inserting All 50 States
INSERT INTO states (name, abbreviation, capital, statehood_date, statehood_order, area_sq_miles, population, motto, nickname, flag_description, flower, bird, famous_for, major_employer, political_orientation, senators, representatives_count, state_tax_info, flag_url)
VALUES
('Alabama', 'AL', 'Montgomery', 'December 14, 1819', 22, 52420, 5108468, 'Audemus jura nostra defendere', 'The Yellowhammer State', 'Crimson St. Andrews cross on white', 'Camellia', 'Yellowhammer', 'Civil Rights, NASA, Football', 'Automotive, Aerospace', 'Republican', '[{"name":"Tommy Tuberville","party":"R"},{"name":"Katie Britt","party":"R"}]', 7, '2% to 5% income tax', 'https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Alabama.svg'),
('Alaska', 'AK', 'Juneau', 'January 3, 1959', 49, 665384, 733406, 'North to the Future', 'The Last Frontier', 'Eight gold stars on blue', 'Forget-me-not', 'Willow Ptarmigan', 'Oil, Northern Lights, Wildlife', 'Oil, Government, Fishing', 'Republican', '[{"name":"Lisa Murkowski","party":"R"},{"name":"Dan Sullivan","party":"R"}]', 1, 'No income tax', 'https://upload.wikimedia.org/wikipedia/commons/e/e6/Flag_of_Alaska.svg'),
('Arizona', 'AZ', 'Phoenix', 'February 14, 1912', 48, 113998, 7431344, 'Ditat Deus', 'The Grand Canyon State', 'Star with 13 rays', 'Saguaro Blossom', 'Cactus Wren', 'Grand Canyon, Desert, Sedona', 'Tech, Manufacturing', 'Democratic', '[{"name":"Kyrsten Sinema","party":"I"},{"name":"Mark Kelly","party":"D"}]', 9, '2.5% flat tax', 'https://upload.wikimedia.org/wikipedia/commons/9/9d/Flag_of_Arizona.svg'),
('Arkansas', 'AR', 'Little Rock', 'June 15, 1836', 25, 53179, 3067732, 'Regnat Populus', 'The Natural State', 'Diamond on red', 'Apple Blossom', 'Mockingbird', 'Hot Springs, Walmart, Ozarks', 'Walmart, Tyson, Logistics', 'Republican', '[{"name":"John Boozman","party":"R"},{"name":"Tom Cotton","party":"R"}]', 4, '2% to 4.4% tax', 'https://upload.wikimedia.org/wikipedia/commons/9/9d/Flag_of_Arkansas.svg'),
('California', 'CA', 'Sacramento', 'September 9, 1850', 31, 163696, 38965193, 'Eureka', 'The Golden State', 'Bear and Star', 'California Poppy', 'California Quail', 'Hollywood, Tech, Wine', 'Tech, Entertainment, Ag', 'Democratic', '[{"name":"Laphonza Butler","party":"D"},{"name":"Alex Padilla","party":"D"}]', 52, '1% to 13.3% tax', 'https://upload.wikimedia.org/wikipedia/commons/0/01/Flag_of_California.svg'),
('Colorado', 'CO', 'Denver', 'August 1, 1876', 38, 104094, 5877610, 'Nil sine numine', 'The Centennial State', 'Blue, white, red C', 'Columbine', 'Lark Bunting', 'Rocky Mountains, Skiing, Beer', 'Aerospace, Energy, Tech', 'Democratic', '[{"name":"Michael Bennet","party":"D"},{"name":"John Hickenlooper","party":"D"}]', 8, '4.4% flat tax', 'https://upload.wikimedia.org/wikipedia/commons/4/46/Flag_of_Colorado.svg'),
('Connecticut', 'CT', 'Hartford', 'January 9, 1788', 5, 5543, 3617176, 'Qui transtulit sustinet', 'The Constitution State', 'Azure with three vines', 'Mountain Laurel', 'American Robin', 'Yale, Insurance, Mystic', 'Insurance, Defense, Finance', 'Democratic', '[{"name":"Richard Blumenthal","party":"D"},{"name":"Chris Murphy","party":"D"}]', 5, '3% to 6.99% tax', 'https://upload.wikimedia.org/wikipedia/commons/9/96/Flag_of_Connecticut.svg'),
('Delaware', 'DE', 'Dover', 'December 7, 1787', 1, 2489, 1018396, 'Liberty and Independence', 'The First State', 'Colonial blue with buff diamond', 'Peach Blossom', 'Blue Hen', 'First State, Corporations', 'Finance, Chemical, Pharma', 'Democratic', '[{"name":"Tom Carper","party":"D"},{"name":"Chris Coons","party":"D"}]', 1, '2.2% to 6.6% tax', 'https://upload.wikimedia.org/wikipedia/commons/c/c6/Flag_of_Delaware.svg'),
('Florida', 'FL', 'Tallahassee', 'March 3, 1845', 27, 65758, 22610726, 'In God We Trust', 'The Sunshine State', 'Red saltire with seal', 'Orange Blossom', 'Northern Mockingbird', 'Disney, Beaches, NASA', 'Tourism, Agriculture, Space', 'Republican', '[{"name":"Marco Rubio","party":"R"},{"name":"Rick Scott","party":"R"}]', 28, 'No income tax', 'https://upload.wikimedia.org/wikipedia/commons/f/f7/Flag_of_Florida.svg'),
('Georgia', 'GA', 'Atlanta', 'January 2, 1788', 4, 59425, 11029227, 'Wisdom, Justice, and Moderation', 'The Peach State', 'Three stripes with coat of arms', 'Cherokee Rose', 'Brown Thrasher', 'Peaches, Coke, Civil Rights', 'Logistics, Beverage, Tech', 'Democratic', '[{"name":"Jon Ossoff","party":"D"},{"name":"Raphael Warnock","party":"D"}]', 14, '1% to 5.49% tax', 'https://upload.wikimedia.org/wikipedia/commons/0/08/Flag_of_the_State_of_Georgia.svg'),
('Hawaii', 'HI', 'Honolulu', 'August 21, 1959', 50, 10931, 1435138, 'Ua mau ke ea o ka aina i ka pono', 'The Aloha State', 'Union Jack with stripes', 'Yellow Hibiscus', 'Nene', 'Surfing, Volcanoes, Luau', 'Tourism, Military, Ag', 'Democratic', '[{"name":"Mazie Hirono","party":"D"},{"name":"Brian Schatz","party":"D"}]', 2, '1.4% to 11% tax', 'https://upload.wikimedia.org/wikipedia/commons/e/ef/Flag_of_Hawaii.svg'),
('Idaho', 'ID', 'Boise', 'July 3, 1890', 43, 83569, 1964726, 'Esto perpetua', 'The Gem State', 'Blue with state seal', 'Syringa', 'Mountain Bluebird', 'Potatoes, Mining, Sun Valley', 'Ag, Tech, Forestry', 'Republican', '[{"name":"Mike Crapo","party":"R"},{"name":"Jim Risch","party":"R"}]', 2, '5.8% flat tax', 'https://upload.wikimedia.org/wikipedia/commons/a/a4/Flag_of_Idaho.svg'),
('Illinois', 'IL', 'Springfield', 'December 3, 1818', 21, 57914, 12549689, 'State Sovereignty, National Union', 'The Land of Lincoln', 'White with state seal', 'Violet', 'Northern Cardinal', 'Chicago, Lincoln, Pizza', 'Finance, Ag, Manufacturing', 'Democratic', '[{"name":"Dick Durbin","party":"D"},{"name":"Tammy Duckworth","party":"D"}]', 17, '4.95% flat tax', 'https://upload.wikimedia.org/wikipedia/commons/0/01/Flag_of_Illinois.svg'),
('Indiana', 'IN', 'Indianapolis', 'December 11, 1816', 19, 36420, 6862199, 'The Crossroads of America', 'The Hoosier State', 'Torch with 19 stars', 'Peony', 'Northern Cardinal', 'Indy 500, Basketball, Corn', 'Manufacturing, Pharma, Ag', 'Republican', '[{"name":"Todd Young","party":"R"},{"name":"Mike Braun","party":"R"}]', 9, '3.05% flat tax', 'https://upload.wikimedia.org/wikipedia/commons/a/ac/Flag_of_Indiana.svg'),
('Iowa', 'IA', 'Des Moines', 'December 28, 1846', 29, 56273, 3207004, 'Our liberties we prize', 'The Hawkeye State', 'Tricolor with eagle', 'Wild Prairie Rose', 'Eastern Goldfinch', 'Ag, Politics, Field of Dreams', 'Ag, Insurance, Food Proc', 'Republican', '[{"name":"Chuck Grassley","party":"R"},{"name":"Joni Ernst","party":"R"}]', 4, '4.4% to 5.7% tax', 'https://upload.wikimedia.org/wikipedia/commons/a/aa/Flag_of_Iowa.svg'),
('Kansas', 'KS', 'Topeka', 'January 29, 1861', 34, 82278, 2940546, 'Ad astra per aspera', 'The Sunflower State', 'Blue with seal and flower', 'Sunflower', 'Western Meadowlark', 'Wizard of Oz, Wheat, Aviation', 'Aviation, Ag, Energy', 'Republican', '[{"name":"Jerry Moran","party":"R"},{"name":"Roger Marshall","party":"R"}]', 4, '3.1% to 5.7% tax', 'https://upload.wikimedia.org/wikipedia/commons/d/da/Flag_of_Kansas.svg'),
('Kentucky', 'KY', 'Frankfort', 'June 1, 1792', 15, 40408, 4526154, 'United we stand', 'The Bluegrass State', 'Blue with seal', 'Goldenrod', 'Northern Cardinal', 'Derby, Bourbon, Fried Chicken', 'Auto, Distilleries, Coal', 'Republican', '[{"name":"Mitch McConnell","party":"R"},{"name":"Rand Paul","party":"R"}]', 6, '4% flat tax', 'https://upload.wikimedia.org/wikipedia/commons/8/8d/Flag_of_Kentucky.svg'),
('Louisiana', 'LA', 'Baton Rouge', 'April 30, 1812', 18, 52378, 4573749, 'Union, justice, confidence', 'The Pelican State', 'Pelican feeding chicks', 'Magnolia', 'Brown Pelican', 'New Orleans, Mardi Gras, Jazz', 'Oil, Tourism, Ag', 'Republican', '[{"name":"Bill Cassidy","party":"R"},{"name":"John Kennedy","party":"R"}]', 6, '1.85% to 4.25% tax', 'https://upload.wikimedia.org/wikipedia/commons/e/e0/Flag_of_Louisiana.svg'),
('Maine', 'ME', 'Augusta', 'March 15, 1820', 23, 35380, 1395722, 'Dirigo', 'The Pine Tree State', 'Blue with pine and moose', 'Pine Cone', 'Chickadee', 'Lobster, Acadia, Lighthouses', 'Tourism, Fishing, Healthcare', 'Democratic', '[{"name":"Susan Collins","party":"R"},{"name":"Angus King","party":"I"}]', 2, '5.8% to 7.15% tax', 'https://upload.wikimedia.org/wikipedia/commons/3/35/Flag_of_Maine.svg'),
('Maryland', 'MD', 'Annapolis', 'April 28, 1788', 7, 12406, 6180253, 'Strong deeds, gentle words', 'The Old Line State', 'Calvert and Crossland arms', 'Black-Eyed Susan', 'Baltimore Oriole', 'Crabs, Naval Academy, Banner', 'Government, Defense, Biotech', 'Democratic', '[{"name":"Ben Cardin","party":"D"},{"name":"Chris Van Hollen","party":"D"}]', 8, '2% to 5.75% tax', 'https://upload.wikimedia.org/wikipedia/commons/a/a0/Flag_of_Maryland.svg'),
('Massachusetts', 'MA', 'Boston', 'February 6, 1788', 6, 10554, 7001399, 'By the sword we seek peace', 'The Bay State', 'White with seal', 'Mayflower', 'Chickadee', 'Harvard, MIT, Red Sox', 'Biotech, Finance, Education', 'Democratic', '[{"name":"Elizabeth Warren","party":"D"},{"name":"Ed Markey","party":"D"}]', 9, '5% flat tax', 'https://upload.wikimedia.org/wikipedia/commons/f/f2/Flag_of_Massachusetts.svg'),
('Michigan', 'MI', 'Lansing', 'January 26, 1837', 26, 96714, 10037261, 'If you seek a pleasant peninsula', 'The Great Lakes State', 'Blue with state seal', 'Apple Blossom', 'American Robin', 'Auto, Lakes, Motown', 'Auto, Manufacturing, Ag', 'Democratic', '[{"name":"Debbie Stabenow","party":"D"},{"name":"Gary Peters","party":"D"}]', 13, '4.25% flat tax', 'https://upload.wikimedia.org/wikipedia/commons/b/b5/Flag_of_Michigan.svg'),
('Minnesota', 'MN', 'Saint Paul', 'May 11, 1858', 32, 86936, 5737915, 'Star of the North', 'The Land of 10,000 Lakes', 'Blue with North Star', 'Lady Slipper', 'Common Loon', '10k Lakes, Mall of America', 'Healthcare, Retail, Ag', 'Democratic', '[{"name":"Amy Klobuchar","party":"D"},{"name":"Tina Smith","party":"D"}]', 8, '5.35% to 9.85% tax', 'https://upload.wikimedia.org/wikipedia/commons/b/b9/Flag_of_Minnesota.svg'),
('Mississippi', 'MS', 'Jackson', 'December 10, 1817', 20, 48432, 2939690, 'By valor and arms', 'The Magnolia State', 'Magnolia with stars', 'Magnolia', 'Mockingbird', 'Blues, River, Elvis', 'Ag, Military, Auto', 'Republican', '[{"name":"Roger Wicker","party":"R"},{"name":"Cindy Hyde-Smith","party":"R"}]', 4, '4% to 5% tax', 'https://upload.wikimedia.org/wikipedia/commons/4/42/Flag_of_Mississippi.svg'),
('Missouri', 'MO', 'Jefferson City', 'August 10, 1821', 24, 69707, 6196156, 'The welfare of the people', 'The Show-Me State', 'Stripes with two bears', 'Hawthorn', 'Eastern Bluebird', 'Arch, BBQ, Mark Twain', 'Aerospace, Healthcare, Ag', 'Republican', '[{"name":"Josh Hawley","party":"R"},{"name":"Eric Schmitt","party":"R"}]', 8, '2% to 4.95% tax', 'https://upload.wikimedia.org/wikipedia/commons/5/5a/Flag_of_Missouri.svg'),
('Montana', 'MT', 'Helena', 'November 8, 1889', 41, 147040, 1132812, 'Gold and Silver', 'The Treasure State', 'Blue with seal', 'Bitterroot', 'Western Meadowlark', 'Glacier, Big Sky, Mining', 'Ag, Mining, Tourism', 'Republican', '[{"name":"Steve Daines","party":"R"},{"name":"Jon Tester","party":"D"}]', 2, '1% to 5.9% tax', 'https://upload.wikimedia.org/wikipedia/commons/c/cb/Flag_of_Montana.svg'),
('Nebraska', 'NE', 'Lincoln', 'March 1, 1867', 37, 77348, 1978379, 'Equality Before the Law', 'The Cornhusker State', 'Blue with gold seal', 'Goldenrod', 'Western Meadowlark', 'Corn, Steaks, Buffett', 'Ag, Insurance, Rail', 'Republican', '[{"name":"Deb Fischer","party":"R"},{"name":"Pete Ricketts","party":"R"}]', 3, '2.46% to 6.6% tax', 'https://upload.wikimedia.org/wikipedia/commons/4/4d/Flag_of_Nebraska.svg'),
('Nevada', 'NV', 'Carson City', 'October 31, 1864', 36, 110572, 3194176, 'All for Our Country', 'The Silver State', 'Blue with silver star', 'Sagebrush', 'Mountain Bluebird', 'Vegas, Gambling, Area 51', 'Tourism, Mining, Tech', 'Democratic', '[{"name":"Catherine Cortez Masto","party":"D"},{"name":"Jacky Rosen","party":"D"}]', 4, 'No income tax', 'https://upload.wikimedia.org/wikipedia/commons/f/f1/Flag_of_Nevada.svg'),
('New Hampshire', 'NH', 'Concord', 'June 21, 1788', 9, 9349, 1402054, 'Live Free or Die', 'The Granite State', 'Blue with seal and frigate', 'Purple Lilac', 'Purple Finch', 'Primary, White Mtns, Fall', 'Tech, Defense, Tourism', 'Republican', '[{"name":"Jeanne Shaheen","party":"D"},{"name":"Maggie Hassan","party":"D"}]', 2, 'No income tax', 'https://upload.wikimedia.org/wikipedia/commons/2/28/Flag_of_New_Hampshire.svg'),
('New Jersey', 'NJ', 'Trenton', 'December 18, 1787', 3, 8723, 9290841, 'Liberty and Prosperity', 'The Garden State', 'Buff with state coat of arms', 'Violet', 'Eastern Goldfinch', 'Shore, Diners, Pharma', 'Pharma, Finance, Tech', 'Democratic', '[{"name":"Cory Booker","party":"D"},{"name":"Bob Menendez","party":"D"}]', 12, '1.4% to 10.75% tax', 'https://upload.wikimedia.org/wikipedia/commons/9/92/Flag_of_New_Jersey.svg'),
('New Mexico', 'NM', 'Santa Fe', 'January 6, 1912', 47, 121590, 2114371, 'It Grows as It Goes', 'The Land of Enchantment', 'Zia sun on yellow', 'Yucca', 'Greater Roadrunner', 'White Sands, Santa Fe Art', 'Natl Labs, Oil, Military', 'Democratic', '[{"name":"Martin Heinrich","party":"D"},{"name":"Ben Ray Lujan","party":"D"}]', 3, '1.7% to 5.9% tax', 'https://upload.wikimedia.org/wikipedia/commons/c/c3/Flag_of_New_Mexico.svg'),
('New York', 'NY', 'Albany', 'July 26, 1788', 11, 54555, 19571216, 'Ever Upward', 'The Empire State', 'Blue with coat of arms', 'Rose', 'Eastern Bluebird', 'NYC, Liberty, Wall St', 'Finance, Tech, Fashion', 'Democratic', '[{"name":"Chuck Schumer","party":"D"},{"name":"Kirsten Gillibrand","party":"D"}]', 26, '4% to 10.9% tax', 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_New_York.svg'),
('North Carolina', 'NC', 'Raleigh', 'November 21, 1789', 12, 53819, 10835491, 'To be rather than to seem', 'The Tar Heel State', 'Red, white, blue with dates', 'Dogwood', 'Northern Cardinal', 'RTP, Outer Banks, BBQ', 'Banking, Tech, Energy', 'Republican', '[{"name":"Thom Tillis","party":"R"},{"name":"Ted Budd","party":"R"}]', 14, '4.5% flat tax', 'https://upload.wikimedia.org/wikipedia/commons/b/bb/Flag_of_North_Carolina.svg'),
('North Dakota', 'ND', 'Bismarck', 'November 2, 1889', 39, 70698, 783926, 'Liberty and union', 'The Peace Garden State', 'Blue with US eagle', 'Prairie Rose', 'Western Meadowlark', 'Oil, Badlands, Roosevlet', 'Oil, Ag, Energy', 'Republican', '[{"name":"John Hoeven","party":"R"},{"name":"Kevin Cramer","party":"R"}]', 1, '1.1% to 2.5% tax', 'https://upload.wikimedia.org/wikipedia/commons/e/ee/Flag_of_North_Dakota.svg'),
('Ohio', 'OH', 'Columbus', 'March 1, 1803', 17, 44826, 11785935, 'With God, all is possible', 'The Buckeye State', 'Swallowtail with buckeye', 'Red Carnation', 'Northern Cardinal', 'Rock Hall, Hall of Fame', 'Manufacturing, Health', 'Republican', '[{"name":"Sherrod Brown","party":"D"},{"name":"J.D. Vance","party":"R"}]', 15, '0% to 3.5% tax', 'https://upload.wikimedia.org/wikipedia/commons/4/4c/Flag_of_Ohio.svg'),
('Oklahoma', 'OK', 'Oklahoma City', 'November 16, 1907', 46, 69899, 4019800, 'Labor conquers all', 'The Sooner State', 'Blue with Osage shield', 'Oklahoma Rose', 'Scissor-tail', 'Oil, Natives, Tornadoes', 'Oil, Aerospace, Ag', 'Republican', '[{"name":"James Lankford","party":"R"},{"name":"Markwayne Mullin","party":"R"}]', 5, '0.25% to 4.75% tax', 'https://upload.wikimedia.org/wikipedia/commons/6/6e/Flag_of_Oklahoma.svg'),
('Oregon', 'OR', 'Salem', 'February 14, 1859', 33, 98379, 4233358, 'She flies with her own wings', 'The Beaver State', 'Two-sided with beaver', 'Oregon Grape', 'Western Meadowlark', 'Nike, Beer, Crater Lake', 'Tech, Forestry, Ag', 'Democratic', '[{"name":"Ron Wyden","party":"D"},{"name":"Jeff Merkley","party":"D"}]', 6, '4.75% to 9.9% tax', 'https://upload.wikimedia.org/wikipedia/commons/b/b9/Flag_of_Oregon.svg'),
('Pennsylvania', 'PA', 'Harrisburg', 'December 12, 1787', 2, 46054, 12961683, 'Virtue, Liberty, Independence', 'The Keystone State', 'Blue with coat of arms', 'Mountain Laurel', 'Ruffed Grouse', 'Liberty Bell, Hershey', 'Health, Energy, Ag', 'Democratic', '[{"name":"Bob Casey Jr.","party":"D"},{"name":"John Fetterman","party":"D"}]', 17, '3.07% flat tax', 'https://upload.wikimedia.org/wikipedia/commons/f/f7/Flag_of_Pennsylvania.svg'),
('Rhode Island', 'RI', 'Providence', 'May 29, 1790', 13, 1545, 1095962, 'Hope', 'The Ocean State', 'White with gold anchor', 'Violet', 'RI Red', 'Newport Mansions, Smallest', 'Health, Education, Defense', 'Democratic', '[{"name":"Jack Reed","party":"D"},{"name":"Sheldon Whitehouse","party":"D"}]', 2, '3.75% to 5.99% tax', 'https://upload.wikimedia.org/wikipedia/commons/f/f3/Flag_of_Rhode_Island.svg'),
('South Carolina', 'SC', 'Columbia', 'May 23, 1788', 8, 32020, 5373555, 'While I breathe, I hope', 'The Palmetto State', 'Indigo with palmetto/moon', 'Yellow Jessamine', 'Carolina Wren', 'Charleston, Myrtle Beach', 'Auto, Tourism, Military', 'Republican', '[{"name":"Lindsey Graham","party":"R"},{"name":"Tim Scott","party":"R"}]', 7, '0% to 6.4% tax', 'https://upload.wikimedia.org/wikipedia/commons/6/69/Flag_of_South_Carolina.svg'),
('South Dakota', 'SD', 'Pierre', 'November 2, 1889', 40, 77116, 919318, 'Under God the people rule', 'The Mount Rushmore State', 'Sky blue with golden sun', 'Pasque Flower', 'Ring-neck Pheasant', 'Rushmore, Badlands', 'Ag, Finance, Tourism', 'Republican', '[{"name":"John Thune","party":"R"},{"name":"Mike Rounds","party":"R"}]', 1, 'No income tax', 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_South_Dakota.svg'),
('Tennessee', 'TN', 'Nashville', 'June 1, 1796', 16, 42144, 7126489, 'Ag and Commerce', 'The Volunteer State', 'Red with three stars', 'Iris', 'Mockingbird', 'Music, Graceland, BBQ', 'Health, Auto, Music', 'Republican', '[{"name":"Marsha Blackburn","party":"R"},{"name":"Bill Hagerty","party":"R"}]', 9, 'No income tax', 'https://upload.wikimedia.org/wikipedia/commons/9/9e/Flag_of_Tennessee.svg'),
('Texas', 'TX', 'Austin', 'December 29, 1845', 28, 268596, 30503301, 'Friendship', 'The Lone Star State', 'Vertical blue with star', 'Bluebonnet', 'Northern Mockingbird', 'Oil, BBQ, NASA, Alamo', 'Oil, Tech, Military', 'Republican', '[{"name":"John Cornyn","party":"R"},{"name":"Ted Cruz","party":"R"}]', 38, 'No income tax', 'https://upload.wikimedia.org/wikipedia/commons/f/f7/Flag_of_Texas.svg'),
('Utah', 'UT', 'Salt Lake City', 'January 4, 1896', 45, 84897, 3417734, 'Industry', 'The Beehive State', 'Blue with beehive', 'Sego Lily', 'California Gull', 'Zion, Skiing, Mormon', 'Tech, Mining, Health', 'Republican', '[{"name":"Mike Lee","party":"R"},{"name":"Mitt Romney","party":"R"}]', 4, '4.65% flat tax', 'https://upload.wikimedia.org/wikipedia/commons/f/f6/Flag_of_Utah.svg'),
('Vermont', 'VT', 'Montpelier', 'March 4, 1791', 14, 9616, 647464, 'Freedom and Unity', 'The Green Mountain State', 'Blue with pine and deer', 'Red Clover', 'Hermit Thrush', 'Maple, B&J, Fall', 'Tourism, Ag, Health', 'Democratic', '[{"name":"Patrick Leahy","party":"D"},{"name":"Bernie Sanders","party":"I"}]', 1, '3.35% to 8.75% tax', 'https://upload.wikimedia.org/wikipedia/commons/4/49/Flag_of_Vermont.svg'),
('Virginia', 'VA', 'Richmond', 'June 25, 1788', 10, 42775, 8683619, 'Thus Always to Tyrants', 'The Old Dominion', 'Blue with goddess Virtus', 'Dogwood', 'Northern Cardinal', 'Jamestown, Arlington', 'Government, Defense, Tech', 'Democratic', '[{"name":"Mark Warner","party":"D"},{"name":"Tim Kaine","party":"D"}]', 11, '2% to 5.75% tax', 'https://upload.wikimedia.org/wikipedia/commons/4/47/Flag_of_Virginia.svg'),
('Washington', 'WA', 'Olympia', 'November 11, 1889', 42, 71298, 7812880, 'By and By', 'The Evergreen State', 'Green with Washington portrait', 'Rhododendron', 'Goldfinch', 'Seattle, Rainier, Tech', 'Tech, Ag, Military', 'Democratic', '[{"name":"Patty Murray","party":"D"},{"name":"Maria Cantwell","party":"D"}]', 10, 'No income tax', 'https://upload.wikimedia.org/wikipedia/commons/5/54/Flag_of_Washington.svg'),
('West Virginia', 'WV', 'Charleston', 'June 20, 1863', 35, 24230, 1770071, 'Mountaineers are always free', 'The Mountain State', 'White with coat of arms', 'Rhododendron', 'Northern Cardinal', 'Coal, Rafting, Peppers', 'Coal, Health, Chemical', 'Republican', '[{"name":"Joe Manchin","party":"D"},{"name":"Shelley Moore Capito","party":"R"}]', 2, '3% to 6.5% tax', 'https://upload.wikimedia.org/wikipedia/commons/2/22/Flag_of_West_Virginia.svg'),
('Wisconsin', 'WI', 'Madison', 'May 29, 1848', 30, 65496, 5893718, 'Forward', 'The Badger State', 'Blue with coat of arms', 'Wood Violet', 'American Robin', 'Cheese, Packers, Beer', 'Ag, Manufacturing, Health', 'Democratic', '[{"name":"Ron Johnson","party":"R"},{"name":"Tammy Baldwin","party":"D"}]', 8, '3.5% to 7.65% tax', 'https://upload.wikimedia.org/wikipedia/commons/2/22/Flag_of_Wisconsin.svg'),
('Wyoming', 'WY', 'Cheyenne', 'July 10, 1890', 44, 97813, 584057, 'Equal Rights', 'The Equality State', 'Blue with bison and star', 'Indian Paintbrush', 'Meadowlark', 'Yellowstone, Devils Tower', 'Mining, Oil, Tourism', 'Republican', '[{"name":"John Barrasso","party":"R"},{"name":"Cynthia Lummis","party":"R"}]', 1, 'No income tax', 'https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Wyoming.svg')
ON CONFLICT (name) DO UPDATE SET
  abbreviation = EXCLUDED.abbreviation,
  capital = EXCLUDED.capital,
  population = EXCLUDED.population,
  senators = EXCLUDED.senators,
  political_orientation = EXCLUDED.political_orientation,
  flag_url = EXCLUDED.flag_url;

-- 4. Set RLS for public read access
ALTER TABLE states ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read" ON states;
CREATE POLICY "Allow public read" ON states FOR SELECT USING (true);
