-- ============================================
-- State Stats: Seed Data for Supabase
-- Run this AFTER create-table.sql
-- Paste this into Supabase SQL Editor and run
-- ============================================

INSERT INTO states (name, abbreviation, capital, statehood_date, statehood_order, area_sq_miles, population, population_year, motto, nickname, flag_description, flower, bird, famous_for, major_employer, political_orientation, senators, representatives_count, state_tax_rate, state_tax_info, flag_url)
VALUES
('Alabama', 'AL', 'Montgomery', 'December 14, 1819', 22, 52420, 5108468, 2024, 'Audemus jura nostra defendere (We Dare Defend Our Rights)', 'The Yellowhammer State', 'A crimson St. Andrew''s cross on a white field, representing Alabama''s ties to the Confederacy and its Scottish-Irish heritage.', 'Camellia', 'Yellowhammer (Northern Flicker)', 'Civil Rights Movement, NASA''s Marshall Space Flight Center, college football', 'Automotive manufacturing (Honda, Hyundai, Mercedes-Benz), aerospace & defense', 'Republican', '[{"name":"Tommy Tuberville","party":"R"},{"name":"Katie Britt","party":"R"}]', 7, 5.00, 'Graduated income tax from 2% to 5%. State sales tax 4%.', 'https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Alabama.svg'),

('Alaska', 'AK', 'Juneau', 'January 3, 1959', 49, 665384, 733583, 2024, 'North to the Future', 'The Last Frontier', 'Eight gold stars on a dark blue field — the Big Dipper and Polaris (North Star) symbolize strength and the state''s northern location.', 'Forget-me-not', 'Willow Ptarmigan', 'Northern Lights, glaciers, oil pipeline, wildlife, Denali (tallest peak in North America)', 'Oil & gas industry, federal government, fishing & seafood', 'Republican', '[{"name":"Lisa Murkowski","party":"R"},{"name":"Dan Sullivan","party":"R"}]', 1, 0, 'No state income tax. No state sales tax. Residents receive annual Permanent Fund Dividend.', 'https://upload.wikimedia.org/wikipedia/commons/e/e6/Flag_of_Alaska.svg'),

('Arizona', 'AZ', 'Phoenix', 'February 14, 1912', 48, 113990, 7431344, 2024, 'Ditat Deus (God Enriches)', 'The Grand Canyon State', '13 red and gold rays radiating from a copper star, representing the original colonies and Arizona''s copper mining heritage.', 'Saguaro Cactus Blossom', 'Cactus Wren', 'Grand Canyon, Sonoran Desert, retirement destination, red rock formations of Sedona', 'Semiconductor manufacturing (Intel, TSMC), aerospace (Raytheon), healthcare', 'Democratic', '[{"name":"Kyrsten Sinema","party":"I"},{"name":"Mark Kelly","party":"D"}]', 9, 2.50, 'Flat 2.5% income tax. State sales tax 5.6%.', 'https://upload.wikimedia.org/wikipedia/commons/9/9d/Flag_of_Arizona.svg'),

('Arkansas', 'AR', 'Little Rock', 'June 15, 1836', 25, 53179, 3067732, 2024, 'Regnat Populus (The People Rule)', 'The Natural State', 'A red, white and blue diamond on a red field. 25 stars surround the diamond representing its position as 25th state.', 'Apple Blossom', 'Mockingbird', 'Hot Springs National Park, Walmart headquarters, rice production, Ozark Mountains', 'Walmart, Tyson Foods, agriculture (poultry, rice), logistics', 'Republican', '[{"name":"John Boozman","party":"R"},{"name":"Tom Cotton","party":"R"}]', 4, 4.40, 'Graduated income tax from 2% to 4.4%. State sales tax 6.5%.', 'https://upload.wikimedia.org/wikipedia/commons/9/9d/Flag_of_Arkansas.svg'),

('California', 'CA', 'Sacramento', 'September 9, 1850', 31, 163696, 38965193, 2024, 'Eureka (I Have Found It)', 'The Golden State', 'A grizzly bear walking on a patch of grass with a red star and red stripe. The bear symbolizes strength and the star represents sovereignty.', 'California Poppy', 'California Quail', 'Hollywood, Silicon Valley, wine country, Golden Gate Bridge, Yosemite', 'Tech (Apple, Google, Meta), entertainment, agriculture, aerospace', 'Democratic', '[{"name":"Laphonza Butler","party":"D"},{"name":"Alex Padilla","party":"D"}]', 52, 13.30, 'Graduated income tax from 1% to 13.3% (highest in US). State sales tax 7.25%.', 'https://upload.wikimedia.org/wikipedia/commons/0/01/Flag_of_California.svg'),

('Colorado', 'CO', 'Denver', 'August 1, 1876', 38, 104094, 5877610, 2024, 'Nil sine numine (Nothing Without Providence)', 'The Centennial State', 'Three horizontal stripes (blue, white, blue) with a red C filled with a golden disk.', 'Rocky Mountain Columbine', 'Lark Bunting', 'Rocky Mountains, skiing, craft beer, outdoor recreation, Pikes Peak', 'Aerospace & defense (Lockheed Martin), tech, energy, tourism', 'Democratic', '[{"name":"Michael Bennet","party":"D"},{"name":"John Hickenlooper","party":"D"}]', 8, 4.40, 'Flat 4.4% income tax. State sales tax 2.9%.', 'https://upload.wikimedia.org/wikipedia/commons/4/46/Flag_of_Colorado.svg'),

('Connecticut', 'CT', 'Hartford', 'January 9, 1788', 5, 5543, 3617176, 2024, 'Qui transtulit sustinet (He Who Transplanted Still Sustains)', 'The Constitution State', 'An azure blue field with a baroque shield bearing three grapevines.', 'Mountain Laurel', 'American Robin', 'Yale University, insurance industry, Mystic Seaport, submarine manufacturing', 'Insurance (Aetna, The Hartford), defense (Electric Boat), finance, healthcare', 'Democratic', '[{"name":"Richard Blumenthal","party":"D"},{"name":"Chris Murphy","party":"D"}]', 5, 6.99, 'Graduated income tax from 3% to 6.99%. State sales tax 6.35%.', 'https://upload.wikimedia.org/wikipedia/commons/9/96/Flag_of_Connecticut.svg'),

('Delaware', 'DE', 'Dover', 'December 7, 1787', 1, 2489, 1018396, 2024, 'Liberty and Independence', 'The First State', 'A colonial blue field with a buff-colored diamond bearing the state coat of arms.', 'Peach Blossom', 'Blue Hen', 'Being the first state to ratify the Constitution, tax-free shopping, DuPont, corporate law', 'Financial services, chemical industry (DuPont), pharmaceutical, poultry farming', 'Democratic', '[{"name":"Tom Carper","party":"D"},{"name":"Chris Coons","party":"D"}]', 1, 6.60, 'Graduated income tax from 2.2% to 6.6%. No state sales tax.', 'https://upload.wikimedia.org/wikipedia/commons/c/c6/Flag_of_Delaware.svg'),

('Florida', 'FL', 'Tallahassee', 'March 3, 1845', 27, 65758, 22610726, 2024, 'In God We Trust', 'The Sunshine State', 'A red saltire on a white field with the state seal in the center.', 'Orange Blossom', 'Northern Mockingbird', 'Walt Disney World, beaches, NASA Kennedy Space Center, Everglades, oranges', 'Tourism, agriculture (citrus, sugar), aerospace (SpaceX), healthcare, finance', 'Republican', '[{"name":"Marco Rubio","party":"R"},{"name":"Rick Scott","party":"R"}]', 28, 0, 'No state income tax. State sales tax 6%.', 'https://upload.wikimedia.org/wikipedia/commons/f/f7/Flag_of_Florida.svg'),

('Georgia', 'GA', 'Atlanta', 'January 2, 1788', 4, 59425, 11029227, 2024, 'Wisdom, Justice, and Moderation', 'The Peach State', 'Three red and white stripes with a blue canton containing the state coat of arms encircled by 13 stars.', 'Cherokee Rose', 'Brown Thrasher', 'Peaches, Coca-Cola, CNN headquarters, Martin Luther King Jr., film industry hub', 'Logistics (Delta, UPS), Coca-Cola, Home Depot, entertainment/film, tech', 'Democratic', '[{"name":"Jon Ossoff","party":"D"},{"name":"Raphael Warnock","party":"D"}]', 14, 5.49, 'Graduated income tax from 1% to 5.49%. State sales tax 4%.', 'https://upload.wikimedia.org/wikipedia/commons/0/08/Flag_of_the_State_of_Georgia.svg')

ON CONFLICT (name) DO UPDATE SET
  abbreviation = EXCLUDED.abbreviation,
  capital = EXCLUDED.capital,
  population = EXCLUDED.population,
  senators = EXCLUDED.senators,
  political_orientation = EXCLUDED.political_orientation;
